### ISSUE TITLE
Problem show data if my router (raspberry)  not connected to Internet

### ISSUE THREAD

**Issue by AnD010** [mavris/MMLanScan#1]
Hi!
I try to use your proyect with a raspberry, my raspberry don´t have internet conexion. Then connect my iphone to wifi network raspberry , run your project and don´t have any response...
If connect my raspberry to internet or connect my iphone to my router with internet, your project work very well.
With ring app , I can see my iphone mac but my raspberry don´t have internet ...
I change AF_INET to AF_LOCAL or AF_UNIX , but don´t work...
I add and use this file in the project 
[http://opensource.apple.com//source/bootp/bootp-133.8/bootplib/arp.c]
but only have mac and ip of my raspberry..
any idea how could get the mac if my iphone is connected to a wireless network without internet?
thanks for your time 

regards!

**Comment by mavris** [comment]
Hi,
I am working on V2 of MMLanScan and I will try to fix it. 
I will release it soon. You can tried yourself the beta V2 on the "development" branch and let me know if you can reproduce the error.
