### ISSUE TITLE
SimplePing.h not found

### ISSUE THREAD

**Issue by thibaultfloquet** [mavris/MMLanScan#10]
Hello, I have an issue when I try to build my project.
The SimplePing.h is not found. Any ideas?

My deployment target is iOS 9.3

Thanks

![capture d ecran 2017-02-15 a 11 22 51](https://cloud.githubusercontent.com/assets/2004156/22970128/46d7f54e-f371-11e6-8c3d-7a0c1b8a2022.png)

**Comment by mavris** [comment]
Hi,
Did you tried one of the demos, install it manually or with Cocoapods?

**Comment by mavris** [comment]
I am closing this issue.
