### ISSUE TITLE
How to getHostName in swift?

### ISSUE THREAD

**Issue by ChoiSeungchan** [mavris/MMLanScan#12]
I tried get hostname in this code

func lanScanDidFindNewDevice(device: Device!) {
//        print("This is Device : "+"\(device)")
        //Adding the found device in the array
        if(device.brand.containsString("Apple")){
        print("DeviceInfo : "+"\(device.macAddressLabel())"+"\(device.hostname)\n")
        }
        self.connectedDevices?.append(device)
    }

but hostName is "nil"

I using swift 2.2 and xcode 7 and also I am beginner developer so I need your help
please tell me how can I get HostName

**Comment by NeverAgain11** [comment]
I also met this question, Did you solved it?

**Comment by mavris** [comment]
Hi,
The getHostname function was not built by me. I noticed also that in some networks (eg. a network with Active Directory) shows the hostnames and in others is not showing. I think it has something to do with the type of DNS. If you find a more solid getHostname function please let me know or send me a pull request.

**Comment by jpalten** [comment]
Perhaps using MDNS or NBNS requests... I'll look into that.

**Comment by Sofianebenabdallah** [comment]
I have the same problem on some network. Some news about this ?

**Comment by Ketan-Wadyalkar** [comment]
I am facing the same issue, hostname is always empty. Any solution ?..

**Comment by fukemy** [comment]
same problem here, any updates?

**Comment by HussainTechGee** [comment]
I am facing the same issue, hostname getting empty on specific networks . Any solution? @Ketan-Wadyalkar @fukemy @Sofianebenabdallah

**Comment by fukemy** [comment]
hostname does not important than MAC address, after ios 11.4 this library does not help to get MAC, so i decided to leave

**Comment by HussainTechGee** [comment]
Thanks for your significant time @fukemy .please recommend any other library for same functionality if you know about that

**Comment by fukemy** [comment]
sorry i am trying to find the library like that :(

**Comment by tanvishah912** [comment]
Anyone found any solution for getting host name?

**Comment by fukemy** [comment]
no solution here bro, the only way is searching for onvif camera ios

**Comment by tanvishah912** [comment]
But how other apps on app store are able to get host names line Fing, Net Analyzer?

**Comment by tanvishah912** [comment]
@fukemy But how other apps on app store are able to get host names like Fing, Net Analyzer?

**Comment by fukemy** [comment]
may be it's were not blocked by Apple, i think so.

**Comment by Sofianebenabdallah** [comment]
Hey, last time I did it it was 2 years ago. Unfortunately, Apple blocked these data. I got these data from mdns. You may need to merge mmlan and mdns data

**Comment by sz-ashik440** [comment]
@Sofianebenabdallah can you give me a lead how to get data from mdns/mmlan.
