### ISSUE TITLE
Why I can't see hostname ?

### ISSUE THREAD

**Issue by ibolat38** [mavris/MMLanScan#13]
cell.ipLabel.text = device.ipAddress
        cell.macAddressLabel.text = device.macAddress
        cell.hostnameLabel.text = device.hostname
        cell.brandLabel.text = device.brand

In this code there is a hostname section but application doesn't show any value about hostname.

**Comment by mavris** [comment]
Hi,
See this issue: https://github.com/mavris/MMLanScan/issues/12
