### ISSUE TITLE
10.3.2 Mac Address Problem

### ISSUE THREAD

**Issue by iremkorkmaz** [mavris/MMLanScan#14]
I can see my device's mac address from another device but when I try to get my device's mac address from the same device what I get is only 02:00:00:00:00:00. How can I fix that?

**Comment by mavris** [comment]
This issue with iOS 10.3. It's Apple's shot to stop the cat & mouse game between them and the developers. They won't let you retrieve your own mac address for privacy but they will let you retrieve others.
