### ISSUE TITLE
not showing in simulator !!

### ISSUE THREAD

**Issue by SelvaBalasubramanian** [mavris/MMLanScan#20]
It shows "no wifi available "in simulatorWhat to do?

**Comment by mavris** [comment]
This is not a bug. The function that retrieves the SSID names it's not working on simulator. Try it on device

**Comment by SelvaBalasubramanian** [comment]
I don't have i phone now....is there any other way to run it on simulator??

**Comment by mavris** [comment]
you can scan the network anyway in simulator. just press the refresh button

**Comment by SelvaBalasubramanian** [comment]
I tried but it shows a popup "Failed to scan "

**Comment by jpalten** [comment]
Strange, that would happen if the app can't find its ip address. Are you on a network at all? IPv4?

**Comment by SelvaBalasubramanian** [comment]
my mac is connected to a wifi network.....and i can even browse in safari in my simulator:(
yet its not scanning...

**Comment by SelvaBalasubramanian** [comment]
@mavris Thanks for ur support this MMLanScanner is very useful.

**Comment by mavris** [comment]
you are welcome dude

**Comment by SelvaBalasubramanian** [comment]
hii,
I have a doubt  i need check whether a entity is present in Core data?if it
is not create a new entity programatically.
how can i check it?
