### ISSUE TITLE
No longer getting MAC address on iOS 11

### ISSUE THREAD

**Issue by CodeNinja710** [mavris/MMLanScan#23]
Using iOS 11.0 beta 1, the current code returns a spoofed mac address. 02:00:00:00:00:00

**Comment by mavris** [comment]
MAC Address of your device or every other device? eg. When you scan the network you can see other devices MAC Addresses but not yours?

**Comment by CodeNinja710** [comment]
All devices show spoofed MAC's. Some devices still show hostname but, not all. Running same code in 10.3 shows all the appropriate info. 
![macaddressspoofed11 0](https://user-images.githubusercontent.com/29494320/27544528-46ca465a-5a42-11e7-9ead-4bfd8f27d64e.png)

**Comment by kasimok** [comment]
Just googled it looks enhanced the security on iOS 11: Check this [link](https://netanalyzer.helpscoutdocs.com/article/119-mac-addresses-arent-available-under-ios-11)

**Comment by wizardguy** [comment]
Not work on iOS 11.0 beta. All returns 02:00. And Find does NOT work neither.

**Comment by ecumedesjours** [comment]
and the countdown to a hackish solution begins once more... :/

**Comment by gregpardo** [comment]
I've reached out to two developers for network utility apps. Both have contacted Apple and have seemed to have made no progress convincing them to at least allow a permission for this. I think this is going to break most network apps when it drops.

**Comment by jeromeof** [comment]
Any sign of any workaround for this issue yet? I noticed with IOS11 GM that all the Network scanning apps like Fing do not work anymore. But would be interested if news of any developer workarounds are being looked at?

**Comment by mavris** [comment]
I am closing this issue since there is no workaround for iOS 11. If you find anything please post it here and reopen the issue.

**Comment by bernikowich-cedoni** [comment]
Hello.
Looks like Fing app creators discovered some workarounds for this issue.

**Comment by fukemy** [comment]
tested Fing and work normally, but this is not

**Comment by maxto024** [comment]
did anyone get a workaround for this issue
