### ISSUE TITLE
SimplePing.h errors for Xcode GM 

### ISSUE THREAD

**Issue by yavuz** [mavris/MMLanScan#29]
When I try to compile with Xcode GM, I get a SimplePing.h error.

Is there anyone testing with Xcode GM?

**Comment by mavris** [comment]
I will check it and let you know. Did you use CocoaPods?

**Comment by jpalten** [comment]
There are some issues for sure. And changes needed.

**Comment by yavuz** [comment]
@mavris git repo and cocoapods. yes, there are some issues in both of them.

**Comment by yavuz** [comment]
**firstly, in Simple.h file. this lines.**

from
`check_compile_time`

to
`__Check_Compile_Time`

I changed it.

**after MacFinder.h file.**

from
`#include <net/route.h>`
to
`#include "route.h"`

that's it. I did temporarily solved.

**Comment by atulvuliv** [comment]
Thanks, I did the above changes and it worked.

**Comment by mavris** [comment]
Hi guys, I fixed the issue. Thanks for your help
