### ISSUE TITLE
xcode9 issues

### ISSUE THREAD

**Issue by ThomasAriano** [mavris/MMLanScan#31]
# SimplePing.h

- check_compile_time  needs to be changed to __Check_Compile_Time

# MacFinder.h

- This seems to be broken now. 'net/route.h' can't be found. Changing to "route.h" (as suggested by another issue) does not seem to fix the problem. MacFinder may have been broken by the iOS 11 crackdown on LanScanners [(relevant link).](https://forums.developer.apple.com/thread/84607)

**Comment by sanghavan** [comment]
I got same issue on Xcode 9.0. on Xcode 8, it's still working.

**Comment by ThomasAriano** [comment]
It looks like anything related to mac addresses will need to be removed/updated. As far as I can tell, the best case here will be returning a list of ip addresses on the network that respond to a ping.

**Comment by sanghavan** [comment]
[route.h.zip](https://github.com/mavris/MMLanScan/files/1335867/route.h.zip)
Just remove the `TARGET_IPHONE_SIMULATOR ` define check in `route.h`, and change 'net/route.h' to "route.h".
``` Remove define check
#if TARGET_IPHONE_SIMULATOR
#else
#endif
```

**Comment by ThomasAriano** [comment]
@sanghavan After adding route.h to the project, I was able to get it to build without any errors, but the program still does not work. When I try to scan, it says that I am not connected to WiFi. Have you actually gotten it to work, or just build?

**Comment by sanghavan** [comment]
@ThomasAriano On your Mac it may have many interfaces as en0, en1. E.g: your Mac has Ethernet and WiFi build-in, then en0 is for Ethernet, en1 is for WiFi. en0 often used for main interface. If your Mac only has no Ethernet, then en0 is for WiFi.

On real device, WiFi is main interface. So en0 should be used.

**Comment by mavris** [comment]
Hi guys, I fixed the errors. Thanks for your help
