### ISSUE TITLE
 Compatibility issues

### ISSUE THREAD

**Issue by situyan** [mavris/MMLanScan#32]
Hi,  

When I run on iOS11, can not get Mac address, I found that you mentioned "iOS 11 is breaking the MAC address retrieval from ARP table so MAC Addresses and Brands won't work on MMLanScan with iOS 11. We still using MacFinder since it's helpful in order to discover online devices that won't reply to pings", where can there be other solutions or ideas? Please tell us.

Thank you very much!

**Comment by mavris** [comment]
At the moment the community didn't come up with work around. So for iOS 11 we can't user MAC Address.

**Comment by situyan** [comment]
well😞,  but still thank you for your answer.
