### ISSUE TITLE
What is the function to scan all the associated IP ?

### ISSUE THREAD

**Issue by Lintes** [mavris/MMLanScan#38]
Hi Mavris,

Here in the function, I can see LANProperties, MMLanScan and others
but I couldn't figure it out  the correct function to call for scanning all the associated IP in a same network.

Please bare with my noviceness and reply me at your earliest

**Comment by saormart** [comment]
Any news on this ?

**Comment by mavris** [comment]
Initialize with delegate

self.lanScanner = [[MMLANScanner alloc] initWithDelegate:self];
Start the scan

[self.lanScanner start];
