### ISSUE TITLE
Question regarding Hostnames

### ISSUE THREAD

**Issue by Manuel83** [mavris/MMLanScan#4]
I'm using MMLanScan for my app but for some reason I don't get all hostnames.
If I use apps like "fing" I get different names. Any hint why I get different results?

![image](https://cloud.githubusercontent.com/assets/5859486/21237722/6b375e58-c300-11e6-8cba-cba134f285c8.png)

**Comment by ecumedesjours** [comment]
they have some code to clean up DNS entries and make them more standardized.  also, they are obtaining additional information from bonjour, snmp and other services and using that to augment the host names.

**Comment by mavris** [comment]
About the formatting, you can change it to be more readable. By the way let me know the name of your app so I will include it in Readme

**Comment by Manuel83** [comment]
First of all thanks for the great project and thanks for you quick response. How do a change the name? Do I have to implement my own formatter logic? For me it would be ok to trigger another request for each IP to get the hostname.

The app I'm building will be called "CraftBeerPi" like the open source home brewing controller project I founded 1,5 years ago.  The App will be used to scan the network for Raspberry Pi and trigger an installation of CraftBeerPi via the app. 

Have a look here. 
https://github.com/Manuel83/craftbeerpi

Cheers
Manuel

**Comment by mavris** [comment]
Let me know the URL when you finish. About the formatting: Just format the NSString you get from hostnameLabel. You could use [device.hostnameLabel uppercaseString] or [hostname componentsSeparatedByString:@"."] which returns an NSArray of NSStrings separated by ".". Now if you get the first object of the NSArrya is the hostname without the "domain". About getting more data like Fing you will have to implement some other techniques like @ecumedesjours  suggested. If you do that, send me a pull request.
