### ISSUE TITLE
The operation couldn’t be completed. Operation not permitted

### ISSUE THREAD

**Issue by anismansuri63** [mavris/MMLanScan#64]
I have a mac catalyst project.
I'm getting below error when I scan.
The operation couldn’t be completed. Operation not permitted

**Comment by Choprarahul** [comment]
Have you found solution for mac catalyst ?

**Comment by anismansuri63** [comment]
Yes.
On your project target, enable both, Incoming and Outgoing connection.

<img width="709" alt="Screenshot 2022-07-22 at 6 13 14 PM" src="https://user-images.githubusercontent.com/16034467/180441551-cdc7799f-c1d2-4447-90f0-3f12bd0c390c.png">
