### ISSUE TITLE
CocoaPods inegration: brand name is not showed

### ISSUE THREAD

**Issue by yongjing** [mavris/MMLanScan#9]
hello @mavris great job for CocoaPods support. I tested the pod, it doesn't work to get the brand name, I think it's because the data.plist file is not included. I creat a Pull Request for this, may fix this little bug.

**Comment by mavris** [comment]
Hi @yongjing . You were right. I fixed the issue. Sorry for not accepting your pull request but I had to change the variable name (you used spec. instead of s.) and I did change the version of PodSpec. Please free to send pull request if you add any new features.

**Comment by yongjing** [comment]
@mavris Yes, my bad for `s`. Nice job! the pod is works now!
